### ISSUE TITLE
hightlight false not working

### ISSUE THREAD

**Issue by Khangeldy** [yumemor/hexo-theme-varaint#5]
After installation. Code highlight not working. Same problem in there 
[Problem](https://camo.githubusercontent.com/bdf871e5cd6a5897ed4b69794898e21524251e77/687474703a2f2f6f63743864316d71662e626b742e636c6f7564646e2e636f6d2f323031362d31312d31302d3039253341313325334132312e6a7067)

**Comment by akarineren** [comment]
This theme not use Hexo highlight ，Fix:

> hexo>_config.yml line 46 - 50

``` yaml
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```
