### ISSUE TITLE
请问highlight属性应该放在哪个位置的_config.yml文件里？

### ISSUE THREAD

**Issue by zhongzilu** [yumemor/hexo-theme-varaint#9]
我放在本主题的_config.yml文件中，可是没有用，我换到hexo的根目录下的_config.yml文件中时，在使用命令：`hexo clean`时就会报错

**Comment by akarineren** [comment]
是 hexo 的 _config.yml，不是主题的

> line 47 - 50
```
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```
 

本身这个属性是存在的 你需要做的是 把  `true` 修改成 `false` 就可以了，不需要去添加 `highlight` 属性
